### ISSUE TITLE
Run nfd without gurobi

### ISSUE THREAD

**Issue by matteocarde** [Kurorororo/numeric-fast-downward#1]
Hi,
I'm trying to run your planner but, since I'm running it on multiple machines on docker, I cannot install Gurobi, due to licencing problems.

Would it be possible to install your planner without having Gurobi installed? I would like to run your planner with the (Kuroiwa et al. 2022) settings.

~~~
[ 19%] Building CXX object search/CMakeFiles/downward.dir/pdbs/canonical_pdbs_heuristic.cc.o
#63 463.8 [ 19%] Building CXX object search/CMakeFiles/downward.dir/pdbs/canonical_pdbs.cc.o
#63 467.4 [ 20%] Building CXX object search/CMakeFiles/downward.dir/gurobi_compilation/relevance_constraints.cc.o
#63 467.9 In file included from /var/nfd/src/search/gurobi_compilation/relevance_constraints.cc:1:0:
#63 467.9 /var/nfd/src/search/gurobi_compilation/relevance_constraints.h:10:10: fatal error: gurobi_c++.h: No such file or directory
#63 467.9  #include "gurobi_c++.h"
#63 467.9           ^~~~~~~~~~~~~~
#63 467.9 compilation terminated.

~~~

Best

**Comment by Kurorororo** [comment]
Hi,

Comment out (use \#) the following lines and then build it.

https://github.com/Kurorororo/numeric-fast-downward/blob/e4611409a7e175af1b0ecf90a3696cc315185a05/src/search/DownwardFiles.cmake#L547-L563
